name: Bump dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: write
  pull-requests: write
  packages: read

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deps-bump:
    name: "Bump dependencies"
    uses: markgaze/automation/.github/workflows/bump.yml@main
    with:
      node-version-file: ".nvmrc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
